### ISSUE TITLE
Allow SUT to be installed externally

### ISSUE THREAD

**Issue by perdelt** [Beuth-Erdelt/Benchmark-Experiment-Host-Manager#176]
* name of sut
* name of service of sut
* labels of sut (dummy pod?)
* for benchmarker
* for loading
* for monitoring
* check loaded
* check running
* start / stop

**Comment by perdelt** [comment]
Simple approach: Overwrite SUT service to be fixed to static one, leave rest for simplicity the same (dummy SUT)

**Comment by perdelt** [comment]
Test
* [ ] YugabyteDB
* [ ] Kinetica
* [ ] SingleStore cluster

**Comment by deenar** [comment]
Hi, does this feature support benchmarking of cloud databases where Benchmark-Experiment-Host-Manager is used only for benchmarking skipping the database hosting feature?

**Comment by perdelt** [comment]
Hello @deenar
Yes, it is possible, but not ready to use out of the box. What is your use case?

**Comment by perdelt** [comment]
@perdelt recheck YugaByteDB

**Comment by perdelt** [comment]
mostly part of #268 now
